#!/usr/bin/env tsx
/**
 * Read every WAV in `assets/samples/` and emit a TypeScript module
 * (`src/stdlib/samples-data.ts`) exporting each as a base64 data URL keyed by
 * its filename (without extension). Samples become available to the runtime
 * via the `@stdlib/samples/<name>` virtual path.
 *
 *   pnpm tsx scripts/encode-samples.ts
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = resolve(__dirname, "..", "assets", "samples");
const OUT_FILE = resolve(__dirname, "..", "src", "stdlib", "samples-data.ts");

const entries = readdirSync(SRC_DIR)
  .filter((f) => extname(f).toLowerCase() === ".wav")
  .sort();

const lines: string[] = [
  "// AUTO-GENERATED by scripts/encode-samples.ts. Do not edit by hand.",
  "// Source: assets/samples/*.wav",
  "",
  "export const STDLIB_SAMPLES: Record<string, string> = {",
];

for (const file of entries) {
  const name = file.replace(/\.wav$/i, "");
  const bytes = readFileSync(resolve(SRC_DIR, file));
  const b64 = bytes.toString("base64");
  lines.push(`  ${JSON.stringify(name)}: "data:audio/wav;base64,${b64}",`);
}

lines.push("};", "");

writeFileSync(OUT_FILE, lines.join("\n"));
console.log(`wrote ${OUT_FILE} (${entries.length} samples)`);
